/* eslint-disable */
// AUTO-GENERATED by scripts/gen-star-stories.mjs — do not edit by hand.
import type { Story } from '@/types'

export const INITIAL_STORIES: Story[] = [
  {
    "id": "story-1",
    "title": "Last-Mile Cost Simulator",
    "company": "Flipkart Minutes",
    "primaryLpIds": [
      "invent-and-simplify",
      "think-big",
      "deliver-results"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Flipkart Minutes, our quick-commerce business was rapidly expanding darkstores across India. Every time we wanted to evaluate a new network configuration—say, adding a darkstore in Whitefield Bangalore or testing different delivery radii—it would take our planning team 2-3 days of manual analysis using static spreadsheets. With 100+ darkstores being planned across PAN-India, this was completely unsustainable. We were making million-dollar network decisions based on outdated assumptions.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"As Manager of Network Automation, I was the single-threaded owner to build a tool that would let us test any network configuration against real demand quickly, so we could make data-driven expansion decisions at speed.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"I built an end-to-end Last-Mile Cost Simulator from scratch in Python. Three key things I did:\n\nFirst, data foundation—I integrated actual order data, real driving distances from Google Maps API, and our existing darkstore footprint. This was critical because earlier tools used straight-line distances which were 30% off from reality.\n\nSecond, simulation engine—I built modular components for demand allocation, vehicle routing, and cost calculation. The simulator could take any input scenario—new darkstore locations, changed catchment areas, different vehicle types—and run a full simulation in under 2 minutes.\n\nThird, stakeholder adoption—I knew the tool was useless if planners didn't use it. I held weekly demos for the planning team, created a self-service interface, and trained 8 planners on the tool. I also worked with the product team to integrate it into their decision workflow.\n\nThe hardest part was getting the 2-minute runtime. Initial version took 45 minutes per simulation. I optimized by using vectorized operations in pandas, parallel processing, and caching frequent computations.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"The Cost Simulator became the standard tool for all network expansion decisions at Flipkart Minutes. Decision time went from 2-3 days to 2 minutes—a 1000x improvement. It enabled us to evaluate 50+ network configurations per week instead of 2-3. Used in expansion decisions across 15+ cities. The simulator also caught a planned darkstore in Pune that would have been 35% over budget, saving ~₹2 Cr in fixed costs.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"Two lessons: First, building tools is 30% engineering and 70% adoption—I underestimated change management initially. Second, performance matters for adoption—if the tool was 5 minutes instead of 2, planners would have stuck with spreadsheets.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "Shows tool-building, network design thinking, PAN-country thinking, and stakeholder adoption—exactly what AMXL JP needs.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-2",
    "title": "12% Cost per Shipment Reduction",
    "company": "Flipkart Large",
    "primaryLpIds": [
      "deliver-results",
      "dive-deep",
      "think-big"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Flipkart Large Supply Chain, we handled large shipments—ACs, refrigerators, TVs, washing machines. Our Cost per Shipment was ₹112, which finance leadership flagged as 18% higher than industry benchmark. The pressure was significant: large appliance e-commerce was growing 40% YoY but margins were getting squeezed. I was asked to bring CPS down to ₹95 within 12 months without hurting our 92% on-time delivery.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"I owned end-to-end network design and optimization for large shipments—accountable for cost, asset utilization, speed, and reliability. The CPS reduction was the headline goal.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"I attacked this on three fronts—a portfolio approach rather than a single big bet.\n\nLever 1: Network redesign. I analyzed 6 months of shipment data—2.5 million shipments. Found that 35% of routes had truck utilization below 60%. Built a custom VRP-based routing solver in Python that allocated the right truck type (32-foot, 22-foot, or 19-foot) based on shipment dimensions, weight, and destination clustering. This generated ₹1.2 Cr/month in savings.\n\nLever 2: National linehaul redesign. I partnered with procurement and linehaul ops to completely rethink vendor mix. Identified 12 vendors who were charging 25% above market for similar lanes. Built target cost models per lane, ran negotiation cycles, and shifted volume to vendors meeting target costs. Negotiated variable costing with top 5 vendors. Delivered ₹3.6 Cr/month savings.\n\nLever 3: Forecast accuracy. Designed monthly supply forecasts incorporating CPS, truck count, and CFT per shipment at route level. This let ops plan fleet better and avoid expensive ad-hoc trips.\n\nThroughout, I had weekly reviews with the VP and monthly with the SVP. When VP pushed back on aggressive vendor negotiation in Q2 (worried about service disruption), I presented data showing 3 backup vendors per lane, and we proceeded with controlled rollout.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"Achieved 12% CPS reduction in one year—₹112 to ₹99. Total monthly savings: ₹4.8 Cr or ₹57.6 Cr/year. On-time delivery actually improved from 92% to 94% because right-truck-type allocation meant fewer split shipments. The VRP solver became a permanent tool used across other regions. I won the Flipkart Large team's annual MVP recognition for this work.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"Cost reduction works best as a portfolio—don't bet on one big lever. Also, vendor management requires both data (target costs) and relationships (negotiation, trust)—pure data approach failed in two early negotiations.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "Heavy/bulky shipments are EXACTLY what AMXL is. CPS reduction with maintained service = exactly what AMXL JP needs.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-3",
    "title": "VRP-Based Routing Solver",
    "company": "Flipkart Large",
    "primaryLpIds": [
      "invent-and-simplify",
      "dive-deep",
      "deliver-results"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Flipkart Large, our routing for Mother Hub to Delivery Hub linehaul was largely manual. Routing managers used Excel and tribal knowledge to assign shipments to trucks. As volume grew to 2.5M+ shipments per month, this manual process became a bottleneck—decisions were inconsistent, often suboptimal. We were running 3-4 trucks where 2 optimized trucks would suffice.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"I needed to build an automated routing system that would allocate the right truck type per shipment cluster and optimize for cost while respecting timing constraints.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"This was a classic Vehicle Routing Problem (VRP) with capacity and time-window constraints.\n\nTechnical approach: I built the solver in Python using OR-tools. Inputs: shipment list with origin, destination, dimensions, weight, time window. Outputs: optimized truck assignments with route sequencing.\n\nKey innovations:\n1. Truck type optimization: Algorithm chose between 32ft, 22ft, 19ft trucks based on cube utilization. Earlier, dispatchers always picked 32ft as default.\n2. Hop additions: Identified routes where adding a 5km hop could combine two partial loads into one full load. Saved 18% in trips on those routes.\n3. Constraints handling: Built in delivery time windows, vehicle availability windows, and customer preferences.\n\nAdoption challenge: Routing managers were skeptical—they'd been doing this for years. I ran a 2-week pilot in Bangalore zone, comparing solver output vs manual routing daily. Solver beat manual by 15-20% in cost on most days. Showed results in weekly ops review. Then rolled out zone by zone over 2 months.\n\nIntegration: Worked with tech team to integrate solver output into the dispatch system, so it became part of their daily workflow rather than a separate tool.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"₹1.2 Cr/month savings from the routing solver alone. That's ₹14.4 Cr/year. Truck utilization improved from 65% to 82%. Tool now used across all regions in Flipkart Large. The solver also caught data quality issues—revealed that 8% of shipment dimensions were entered incorrectly, leading to a separate data quality initiative.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"OR-tools is a fantastic library, but the real work is constraint definition and stakeholder buy-in. Also, automation reveals data quality issues you didn't know existed.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "Automated routing for heavy shipments = directly applicable. VRP knowledge is gold for AMXL planning.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-4",
    "title": "National Linehaul Network Redesign",
    "company": "Flipkart Large",
    "primaryLpIds": [
      "think-big",
      "earn-trust",
      "deliver-results"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"Flipkart Large's linehaul network had grown organically over 3 years—we had 80+ vendors across India with no systematic vendor strategy. Vendor rates varied 25-30% on similar lanes. We didn't have target costs or systematic negotiations. Procurement was reactive, signing whatever vendors approached us.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"I led the redesign of the national linehaul network end-to-end—a 6-month strategic initiative covering vendor strategy, cost targets, contract structure, and execution.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"This was a cross-functional program—I had no formal authority over procurement or operations, but I owned the outcome.\n\nStep 1: Diagnostic (Month 1). Analyzed lane-level vendor performance across 200+ lanes. Built target cost models using benchmark data, fuel cost components, distance, and toll. Identified that we were 22% overpaying on average.\n\nStep 2: Vendor strategy (Month 2). Categorized vendors into Strategic (top 15%, get more volume), Performing (60%, hold), and Underperforming (25%, exit). Got procurement on board by sharing data weekly and listening to their constraints (e.g., vendor relationships matter for service recovery).\n\nStep 3: Negotiation playbook (Months 2-3). Built target costs per lane, prepared market intelligence, role-played negotiations with procurement. Introduced variable costing—rates that flex with fuel prices, so vendors didn't need 15% cushion in fixed rates.\n\nStep 4: Execution (Months 3-5). Rolled out lane by lane, top 50 lanes first. Hand-held procurement through first 10 negotiations. Built dashboards to track savings vs target.\n\nStep 5: Stabilize (Month 6). Some vendors threatened exit—we worked with backup vendors. Two lanes had 3-week service issues during transition; I personally coordinated with ops to manage.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"Delivered ₹3.6 Cr/month in savings, ₹43 Cr/year. This was 6% of total linehaul spend. Vendor count rationalized from 80 to 35 strategic vendors. Service quality maintained at 94%+ throughout transition. Procurement adopted the target cost framework as standard practice for future negotiations. Won 'Delivering the Extra Mile' award from Delhivery leadership.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"Cross-functional partnership requires patience. Procurement initially saw me as the analytics guy questioning their judgment. Took 2 months of building trust before they fully partnered. Lesson: lead with curiosity about their world, not with your conclusions.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "Vendor management is huge for AMXL (delivery partners). Cost reduction at scale. Cross-functional leadership.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-5",
    "title": "Diwali Peak S&OP Planning",
    "company": "Shadowfax",
    "primaryLpIds": [
      "think-big",
      "bias-for-action",
      "ownership"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Shadowfax, Diwali peak (October-November) is our Super Bowl—volumes go up 3x in 6 weeks. In previous years, we'd been reactive—ad-hoc capacity additions, last-minute partner onboarding, expensive emergency trucks. Cost per shipment would spike 25% during peak. CEO wanted a fundamentally different approach.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"I was Senior Planning Manager for the e-commerce network. I was asked to lead Diwali peak planning starting 5 months in advance—a first for the company.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"This was the longest planning horizon I'd ever owned. Approach:\n\nMonth 1 (May): Demand forecast. Worked with sales team to get client-level forecasts. Layered macro factors—shopping festival dates, promotional intensity. Built demand model with confidence intervals (P50, P90).\n\nMonth 2 (June): Network design. Identified that we needed middle-mile cross-dock centers in 4 cities (Surat, Lucknow, Indore, Coimbatore) to handle surge. These would let us shift volume from constrained metros. Built business case—₹40 lakh setup cost, projected ₹2 Cr in peak period savings.\n\nMonth 3 (July): Capacity contracts. Locked in linehaul capacity 3 months before peak. Negotiated 30% lower rates than spot market by giving vendors volume guarantees. Onboarded 2 new partners as backup.\n\nMonth 4 (August): Operational readiness. Worked with ops to run mock peak weeks—simulated 2x volume on existing setup, identified bottlenecks. Set up war room cadence, escalation matrix, real-time dashboards.\n\nMonth 5 (September): Final dry run. Ran one weekend at 1.5x volume. Caught issues with specific cross-dock operations. Fixed before peak.\n\nPeak (October-November): Daily war room calls, real-time monitoring. Hit one major snag when one cross-dock center had labor strike—activated backup plan within 12 hours.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"Reduced ad-hoc costs by 18% during peak vs previous year. Maintained CPS within 8% of normal (vs historical 25% spike). Hit 95% on-time even during peak weeks. Scaled volume by 2.5 lakh additional monthly orders. The 5-month-in-advance approach became standard for all future peaks at Shadowfax. Won Mr. Dependable Award.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"Long-horizon planning is uncomfortable—people want to defer decisions. But compounding benefits are huge. Also: dry runs save you in real peaks. The labor strike scenario we'd already war-gamed.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "Mid-to-long-term planning (5 months!), capacity allocation, peak season planning—all directly applicable to Prime Day/seasonal AMXL planning.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-6",
    "title": "TMS Implementation",
    "company": "Shadowfax",
    "primaryLpIds": [
      "invent-and-simplify",
      "hire-and-develop-the-best",
      "ownership"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Shadowfax, our trip creation and dispatch was 80% manual—dispatchers used WhatsApp groups, phone calls, and Excel sheets to coordinate trips. As volume grew to 5M monthly orders, this manual approach was breaking. Trip data was inconsistent, billing was a nightmare, accruals had 15% error rate.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"I led the implementation of the TMS Trip Module and Master Scheduling system—replacing manual processes with automated trip creation and lifecycle management.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"Implementing a TMS isn't just deploying software—it's changing how 200+ dispatchers work daily.\n\nPhase 1: Requirements & buy-in (Month 1). Spent 2 weeks shadowing dispatchers across 5 hubs. Documented their workflows, pain points, and concerns. Built a requirements document with their input. Shared back to dispatchers—'this is what I heard you say'—built trust.\n\nPhase 2: Configuration (Months 2-3). Worked with TMS vendor to configure for our use cases. Made 40+ configuration decisions—trip creation rules, automated billing logic, exception handling. Integrated with our existing order management system.\n\nPhase 3: Pilot (Month 4). Selected one hub (Bangalore) for pilot. Trained 30 dispatchers. Ran parallel for 2 weeks—old process and new process side by side. Caught and fixed 15 bugs/issues.\n\nPhase 4: Rollout (Months 5-7). Hub by hub rollout. I personally went to first 5 hubs for go-live. Set up daily war room for first 2 weeks of each rollout. Created super-users in each hub who became local champions.\n\nPhase 5: Stabilize (Month 8). Built monitoring dashboards—trip creation accuracy, billing variance, dispatcher productivity. Tracked adoption metrics.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"100% trip automation across all hubs within 8 months. Billing accuracy improved from 85% to 98%. Accrual error rate from 15% to 3%. Dispatcher productivity up 40%—same team handled 50% more volume. Created super-user network of 25 trained champions across India. The TMS continues to be foundational system at Shadowfax.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"Change management is harder than technology. The dispatchers who'd been doing this for 10 years were the hardest to convert. What worked: making them part of design, not subjects of change. Five of those skeptics became my biggest champions.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "TMS = directly relevant to AMXL's planning tools. Change management at scale. Building capability across organization.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-7",
    "title": "Multi-Run Connection Logic",
    "company": "Delhivery",
    "primaryLpIds": [
      "invent-and-simplify",
      "frugality",
      "dive-deep"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Delhivery, our sortation centers had a problem: shipments arrived from origin hubs, sat in staging for hours, then got loaded onto outgoing trucks. Staging area was 200,000 sq. ft. across major sortation centers—massive real estate cost. As volume grew, we were running out of staging space.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"As Program Manager - Network Design, I was asked to find ways to reduce staging space requirements without slowing down throughput.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"This required deep dive into how shipments flowed through the sortation centers.\n\nInvestigation: I spent 4 days physically at the Mumbai sortation center. Tracked 50 shipments end-to-end. Found that 30% of shipments arrived and departed within 30-minute windows—they sat in staging unnecessarily because we processed in batches.\n\nInsight: If we could time the arrival of one truck to the departure of another, we could 'direct load'—skip staging entirely. The shipment just transfers from arriving truck to departing truck.\n\nDesign: I built a 'multi-run connection logic' algorithm that:\n1. Identified pairs of arriving/departing trucks with overlapping shipment destinations\n2. Calculated optimal arrival timings to enable direct loading\n3. Adjusted dispatch schedules to create these connections\n\nPilot: Started with Mumbai—the most space-constrained center. Worked with operations team to align truck schedules. First week was rough—two truck delays caused missed connections, shipments piled up. Adjusted algorithm to add 15-minute buffer.\n\nScale: Rolled out to 8 major sortation centers over 4 months. Built tracking dashboard for direct-load percentage.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"Saved 39,000 sq. ft. of staging space across the network—~20% reduction. Reduced manpower cost by ₹40 lakh/year (less manual handling). Direct-load percentage went from 8% to 35%. Used as a model for other Delhivery sortation expansions—new centers were designed with smaller staging from the start.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"Best ideas come from spending time on the floor, not at a desk. The 4 days I spent watching operations gave me insights I couldn't have gotten from data alone. Also: real-world physical constraints (truck delays) require buffer—pure optimization fails.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "Operations excellence, spatial optimization, on-the-floor insights—shows you'll dive deep in AMXL operations too.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-8",
    "title": "Vendor Bidding App",
    "company": "Delhivery",
    "primaryLpIds": [
      "invent-and-simplify",
      "earn-trust",
      "customer-obsession"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Delhivery, third-party vendor onboarding was painful. Procurement would email 5-10 vendors per lane, get quotes via email, manually compare in Excel, negotiate over phone, finalize over email. Took 2-3 weeks per vendor. Decisions weren't always rational—best price didn't always win because comparing apples-to-apples was hard.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"I partnered with product and procurement teams to design a vendor bidding application that would streamline the entire procurement process.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"This was a side project I championed because I saw the inefficiency. No one asked me to do it.\n\nDiscovery: Spent time with procurement team to understand their workflow. Pain points: email overload, comparison difficulty, negotiation back-and-forth, no audit trail.\n\nPitch: Built a one-page proposal with rough mockups. Showed it to procurement head and product team. Got buy-in for 2-month MVP build.\n\nRequirements: Worked with product manager to design:\n- Vendor portal (vendors submit bids)\n- Procurement dashboard (compare bids on standardized parameters)\n- Auto-comparison logic (price, payment terms, capacity, performance history)\n- Negotiation workflow (counter-offer feature)\n- Approval workflow (multi-level)\n\nBuild phase: I provided business requirements and user stories. Worked with 1 engineer and 1 designer. Tested with procurement team weekly.\n\nRollout: Started with linehaul vendors. Trained procurement team. Onboarded 30 vendors in first month—they actually liked it because it was faster than email back-and-forth.\n\nAdoption: Within 6 months, 80% of vendor bidding moved to the app. Created vendor scorecard within app for performance tracking.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"Generated ₹1.3 Cr annual savings on third-party vendor costs—through better comparison and competitive bidding. Reduced vendor onboarding time from 2-3 weeks to 5 days. Created audit trail and structured data for analytics. Procurement team productivity up 30%. App is still used today, with 200+ vendors active.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"You don't need a mandate to drive change—identify a clear pain point, build a small prototype, and let results speak. Also: side projects done well can have outsized impact—this was 20% of my time but probably 30% of my year-end review impact.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "Tool building, vendor management, partnering with product team—all relevant.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-9",
    "title": "Last-Mile Beat Optimiser",
    "company": "Flipkart Minutes",
    "primaryLpIds": [
      "customer-obsession",
      "deliver-results",
      "dive-deep"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Flipkart Minutes, our hyperlocal delivery (10-15 minute promise) was struggling on two metrics: vehicle cost as % of GMV was 6.2% (industry benchmark 4-5%), and on-time picking at FCs was 78%. These directly hurt unit economics and customer experience.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"I built the Last-Mile Beat Optimiser to address both metrics—a tool that would optimize delivery beats (sequences) for our hyperlocal riders.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"Hyperlocal is different from standard last-mile—super short delivery windows, riders return to darkstore between deliveries, demand patterns change hourly.\n\nResearch: Studied 1 month of order data. Found 3 patterns:\n1. Order density was concentrated in 30% of zones during 60% of time\n2. Riders often did 'reverse beats'—going east then west then east again, losing time\n3. FC picking wasn't aligned to delivery sequence—pickers picked random orders, riders waited\n\nDesign: Built Beat Optimiser with three modules:\n1. Beat sequencing: Optimal sequence for rider's 4-6 stops\n2. Rider-order matching: Right rider for the right beat (based on rider location, vehicle type, performance)\n3. FC pick prioritization: Pick orders in the sequence rider will deliver\n\nImplementation: Integrated with rider app and FC pick system. Rolled out city by city—Bangalore first, then Mumbai, then Delhi.\n\nAdoption challenges: Riders complained that algorithm-assigned beats sometimes 'felt wrong'—e.g., not allowing them to choose orders. Did focus groups, learned that riders valued autonomy. Added an override feature with 1-click acceptance of suggested beat.\n\nMetrics tracked: Vehicle cost/GMV, on-time picking, rider productivity, customer NPS.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"Vehicle cost/GMV reduced from 6.2% to 4.5%—a 27% improvement. On-time picking improved from 78% to 92%. Customer NPS up 8 points. Rider productivity up 22%. Tool became core part of Flipkart Minutes operations across all cities. Won E-Kart Awards 2025 for route design automation.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"Optimization tools fail without user empathy. The override feature was a small thing but doubled adoption. Lesson: trust your users' intelligence—give them autonomy with smart defaults.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "Delivery optimization, customer obsession, balancing automation with user experience.",
    "estimatedMinutes": 2.75
  },
  {
    "id": "story-10",
    "title": "VRP-Based Zonal Linehaul Optimization",
    "company": "Delhivery",
    "primaryLpIds": [
      "invent-and-simplify",
      "deliver-results",
      "dive-deep"
    ],
    "sections": [
      {
        "label": "situation",
        "title": "Situation (~30s)",
        "content": "\"At Delhivery, zonal linehaul (within-state truck movements) was a $50M+ annual spend. Routes were planned manually by zonal managers based on experience. As we expanded to more zones, manual planning quality varied—some zones had ₹1.5/shipment cost, others ₹3.2/shipment for similar profiles.\"",
        "timingPct": 30
      },
      {
        "label": "task",
        "title": "Task (~15s)",
        "content": "\"I owned the program to implement VRP-based automation for zonal linehaul route optimization across all major zones.\"",
        "timingPct": 15
      },
      {
        "label": "action",
        "title": "Action (~90s)",
        "content": "\"This was my first major VRP implementation—built the foundation for what I later did at Flipkart.\n\nApproach: Build once, deploy everywhere. Couldn't build a custom solution per zone.\n\nStep 1: Standardize. Worked with 8 zonal managers to understand their routing approaches. Identified 12 common constraints: vehicle capacity, time windows, hub timings, driver hours, road restrictions, fuel costs, return loads, multi-stop sequencing.\n\nStep 2: Build. Used OR-tools for the optimization engine. Built data pipelines to pull shipment data, vehicle availability, distance matrices. Output was a route plan per zone per day.\n\nStep 3: Validate. Compared algorithm output to manual routing for 2 weeks in 2 zones (Maharashtra, Karnataka). Algorithm was 10-15% better in cost, but had 5% more route changes day-to-day (managers preferred stability).\n\nStep 4: Tune. Added stability constraint—algorithm would only suggest route change if savings >8%. This reduced 'churn' while preserving most savings.\n\nStep 5: Roll out. Zone by zone over 6 months. Trained zonal managers as power users—not replacing their judgment but augmenting it. Built feedback loop for continuous improvement.\n\nStep 6: Govern. Set up monthly review—zone managers, central team, finance. Tracked savings, exceptions, manager satisfaction.\"",
        "timingPct": 90
      },
      {
        "label": "result",
        "title": "Result (~30s)",
        "content": "\"₹1 Cr/month savings = ₹12 Cr/year on zonal linehaul. Cost per shipment normalized across zones to ₹2.1 average. Zonal managers shifted from doing routing to managing exceptions and improvements—higher-value work. The framework was so successful that it became foundational for my Flipkart Large work later.\"",
        "timingPct": 30
      },
      {
        "label": "learning",
        "title": "Learning",
        "content": "\"Algorithms augment judgment, not replace it. The stability constraint was a learning—pure optimization without considering organizational reality fails. Also: ₹1 Cr/month sounds impressive, but it took 6 months of careful rollout—patience is part of program management.\"",
        "timingPct": 0
      }
    ],
    "killerAmxl": "VRP at scale, change management, building foundational tools.",
    "estimatedMinutes": 2.75
  }
] as Story[]
